1class Solution {
2public:
3    bool isBalanced(TreeNode* root) {
4        // If the tree is empty, we can say it’s balanced...
5        if (root == NULL)  return true;
6        // Height Function will return -1, when it’s an unbalanced tree...
7		if (Height(root) == -1)  return false;
8		return true;
9	}
10    // Create a function to return the “height” of a current subtree using recursion...
11	int Height(TreeNode* root) {
12        // Base case...
13		if (root == NULL)  return 0;
14        // Height of left subtree...
15		int leftHeight = Height(root->left);
16        // Height of height subtree...
17		int rightHight = Height(root->right);
18        // In case of left subtree or right subtree unbalanced or their heights differ by more than ‘1’, return -1...
19		if (leftHeight == -1 || rightHight == -1 || abs(leftHeight - rightHight) > 1)  return -1;
20        // Otherwise, return the height of this subtree as max(leftHeight, rightHight) + 1...
21		return max(leftHeight, rightHight) + 1;
22    }
23};